/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thomasbotsford.oop.cw1;

import javax.swing.JOptionPane;

/**
 *
 * @author tom
 */
public class newGame extends javax.swing.JFrame {

    /**
     * Creates new form newGame
     */
    public newGame() {
        initComponents();
    }
    
    //method to display the form
    public static void createFrame(){
        java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new newGame().setVisible(true);
                }
            });    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxHomeTeam = new javax.swing.JComboBox<>();
        jComboBoxAwayTeam = new javax.swing.JComboBox<>();
        jTextFieldHomeScore = new javax.swing.JTextField();
        jTextFieldAwayScore = new javax.swing.JTextField();
        jLabelHomeTeam = new javax.swing.JLabel();
        jLabelAwayTeam = new javax.swing.JLabel();
        jButtonAddGame = new javax.swing.JButton();
        jLabelRef = new javax.swing.JLabel();
        jComboBoxRef = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxHomeTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { leagueTable.team1.getName(), leagueTable.team2.getName(), leagueTable.team3.getName(), leagueTable.team4.getName(), leagueTable.team5.getName(), leagueTable.team6.getName(), leagueTable.team7.getName(), leagueTable.team8.getName() }));

        jComboBoxAwayTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { leagueTable.team1.getName(), leagueTable.team2.getName(), leagueTable.team3.getName(), leagueTable.team4.getName(), leagueTable.team5.getName(), leagueTable.team6.getName(), leagueTable.team7.getName(), leagueTable.team8.getName() }));

        jTextFieldHomeScore.setText("Score");
        jTextFieldHomeScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHomeScoreActionPerformed(evt);
            }
        });

        jTextFieldAwayScore.setText("Score");

        jLabelHomeTeam.setText("Home Team");

        jLabelAwayTeam.setText("Away Team");

        jButtonAddGame.setText("Add Game");
        jButtonAddGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddGameActionPerformed(evt);
            }
        });

        jLabelRef.setText("Referee");

        jComboBoxRef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { leagueTable.refList.get(0).getName(), leagueTable.refList.get(1).getName(), leagueTable.refList.get(2).getName(), refereeInfo.jLabelRef4.getText(), refereeInfo.jLabelRef5.getText(), refereeInfo.jLabelRef6.getText()}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddGame))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxHomeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelHomeTeam)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jTextFieldHomeScore, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxAwayTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabelAwayTeam))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jTextFieldAwayScore, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jComboBoxRef, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRef)
                        .addGap(57, 57, 57))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHomeTeam)
                    .addComponent(jLabelAwayTeam)
                    .addComponent(jLabelRef))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAwayTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxHomeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHomeScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAwayScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButtonAddGame)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldHomeScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHomeScoreActionPerformed
        // unused handler
    }//GEN-LAST:event_jTextFieldHomeScoreActionPerformed

    /** event handler for add game button
     * checks selected object names from combo boxes and sets respective object to variables
     * produces error message if both teams are the same
     * constructs new game using set variables and refreshes leagueTable and closes newGame form
     * catches format exception if scores are not numeric and produces error message pop-up
     */
    private void jButtonAddGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddGameActionPerformed
        // initialising variables for game constructor
        team selectedHomeTeam = leagueTable.team1;
        team selectedAwayTeam = leagueTable.team2;
        referee selectedRef = leagueTable.refList.get(0);       
        //set variable to object if combo box string selection matches object name
        if(jComboBoxHomeTeam.getSelectedItem() == leagueTable.teams[0].getName()){
            selectedHomeTeam = leagueTable.team1;
        }
        else if(jComboBoxHomeTeam.getSelectedItem() == leagueTable.teams[1].getName()){
            selectedHomeTeam = leagueTable.team2;
        }
        else if(jComboBoxHomeTeam.getSelectedItem() == leagueTable.teams[2].getName()){
            selectedHomeTeam = leagueTable.team3;
        }
        else if(jComboBoxHomeTeam.getSelectedItem() == leagueTable.teams[3].getName()){
            selectedHomeTeam = leagueTable.team4;
        }
        else if(jComboBoxHomeTeam.getSelectedItem() == leagueTable.teams[4].getName()){
            selectedHomeTeam = leagueTable.team5;
        }
        else if(jComboBoxHomeTeam.getSelectedItem() == leagueTable.teams[5].getName()){
            selectedHomeTeam = leagueTable.team6;
        }
        else if(jComboBoxHomeTeam.getSelectedItem() == leagueTable.teams[6].getName()){
            selectedHomeTeam = leagueTable.team7;
        }
        else if(jComboBoxHomeTeam.getSelectedItem() == leagueTable.teams[7].getName()){
            selectedHomeTeam = leagueTable.team8;
        }
        if(jComboBoxAwayTeam.getSelectedItem() == leagueTable.teams[0].getName()){
            selectedAwayTeam = leagueTable.team1;
        }
        else if(jComboBoxAwayTeam.getSelectedItem() == leagueTable.teams[1].getName()){
            selectedAwayTeam = leagueTable.team2;
        }
        else if(jComboBoxAwayTeam.getSelectedItem() == leagueTable.teams[2].getName()){
            selectedAwayTeam = leagueTable.team3;
        }
        else if(jComboBoxAwayTeam.getSelectedItem() == leagueTable.teams[3].getName()){
            selectedAwayTeam = leagueTable.team4;
        }
        else if(jComboBoxAwayTeam.getSelectedItem() == leagueTable.teams[4].getName()){
            selectedAwayTeam = leagueTable.team5;
        }
        else if(jComboBoxAwayTeam.getSelectedItem() == leagueTable.teams[5].getName()){
            selectedAwayTeam = leagueTable.team6;
        }
        else if(jComboBoxAwayTeam.getSelectedItem() == leagueTable.teams[6].getName()){
            selectedAwayTeam = leagueTable.team7;
        }
        else if(jComboBoxAwayTeam.getSelectedItem() == leagueTable.teams[7].getName()){
            selectedAwayTeam = leagueTable.team8;
        }
        if(jComboBoxRef.getSelectedItem() == leagueTable.refList.get(0).getName()){
            selectedRef = leagueTable.refList.get(0);
        }
        else if(jComboBoxRef.getSelectedItem() == leagueTable.refList.get(1).getName()){
            selectedRef = leagueTable.refList.get(1);
        }
        else if(jComboBoxRef.getSelectedItem() == leagueTable.refList.get(2).getName()){
            selectedRef = leagueTable.refList.get(2);
        }
        else if(jComboBoxRef.getSelectedItem() == leagueTable.refList.get(3).getName()){ 
            selectedRef = leagueTable.refList.get(3);
        }      
        else if(jComboBoxRef.getSelectedItem() == leagueTable.refList.get(4).getName()){ 
                    selectedRef = leagueTable.refList.get(4);
                }      
        else if(jComboBoxRef.getSelectedItem() == leagueTable.refList.get(5).getName()){ 
                    selectedRef = leagueTable.refList.get(5);
                }      
            
        if(selectedHomeTeam == selectedAwayTeam){
            JOptionPane.showMessageDialog(this, "Please select two different teams.");
        }
        else{
            try{
                new game(selectedHomeTeam, selectedAwayTeam,Integer.parseInt(jTextFieldHomeScore.getText()), Integer.parseInt(jTextFieldAwayScore.getText()), selectedRef);                     
                System.out.println(selectedHomeTeam.getName() + " now has " + selectedHomeTeam.getPoints()+ " and " + selectedAwayTeam.getName() + " has " + selectedAwayTeam.getPoints());
                System.out.println(selectedRef.getName() + " now has " + selectedRef.games);
                this.dispose();
                leagueTable.refresh();
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Please enter numeric scores.");
            }
        }
    }//GEN-LAST:event_jButtonAddGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddGame;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxAwayTeam;
    private javax.swing.JComboBox<String> jComboBoxHomeTeam;
    private javax.swing.JComboBox<String> jComboBoxRef;
    private javax.swing.JLabel jLabelAwayTeam;
    private javax.swing.JLabel jLabelHomeTeam;
    private javax.swing.JLabel jLabelRef;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAwayScore;
    private javax.swing.JTextField jTextFieldHomeScore;
    // End of variables declaration//GEN-END:variables
}
